<div class="container-fluid header">

<div class="inside-header">

<div class="container-fluid">
  <div class="header-first-row header-rows-responsive">

    <div class="item search-item-left-right">
      <div class="itm-con-inline-block itm-con-align-center itm-con-margin-top">
        <i class="fas fa-search search-fa-size heeader-fa-color-white"></i>
      </div>
        <div class="itm-con-inline-block itm-con-align-center">
      </div>
    </div>

    <div class="first-row-ver-line"></div>

    <div class="item first-row-item-margin item-margin-top">
      <div class="itm-con-inline-block itm-con-align-center">
        <i class="fas fa-check-circle fa-sm header-fa-color-red fa-first-row-margin"></i>
      </div>
      <div class="itm-con-inline-block itm-con-align-center">
        <p class="text-color-red">Checkout</p>
      </div>
    </div>

    <div class="item first-row-item-margin item-margin-top">
      <div class="itm-con-inline-block itm-con-align-center">
        <i class="fas fa-cart-plus fa-sm header-fa-color-red fa-first-row-margin"></i>
      </div>
      <div class="itm-con-inline-block itm-con-align-center">
        <p class="text-color-red">Cart</p>
      </div>
    </div>

    <div class="item first-row-item-margin item-margin-top">
      <div class="itm-con-inline-block itm-con-align-center">
        <i class="fas fa-user fa-sm header-fa-color-red fa-first-row-margin"></i>
      </div>
      <div class="itm-con-inline-block itm-con-align-center">
        <p class="text-color-red">My account</p>
      </div>
    </div>

  </div>
</div> 

<div class="container-fluid"> 
  <div class="h-row-horizontal-line">
    <div class="header-horisontal-line"></div>
  </div>
</div>

<div class="container-fluid">
  <div class="header-second-row header-rows-responsive">
    <div class="my-cart-item ">
      <div class="itm-con-block itm-con-align-center icon-margin-left-right">
        <i class="fas fa-shopping-cart fa-lg header-fa-color-red h-fa-font-size"></i>
      </div>
      <div class="itm-con-block itm-con-align-center">
        <p class="text-color-white par-margin-top">MY CART</p>
      </div>
    </div>

    <div class="second-row-ver-line"></div>

    <div class="item-second-row-compare item-margin-left-right">
      <div class="itm-con-block itm-con-align-center icon-margin-left-right">
        <i class="fas fa-car header-fa-color-red fa-compare-size"></i>
      </div>
      <div class="itm-con-block itm-con-align-center">
        <p class="text-color-white par-margin-top-compare">COMPARE</p>
      </div>
    </div>

    <div class="second-row-ver-line"></div>

    <div class="item-second-row item-margin-left-right">
      <div class="itm-con-block itm-con-align-center icon-margin-left-right">
        <i class="fas fa-star fa-lg header-fa-color-red h-fa-font-size"></i>
      </div>
      <div class="itm-con-block itm-con-align-center">
        <p class="text-color-white par-margin-top">WISHLIST</p>
      </div>
    </div>

    <div class="second-row-ver-line"></div>

    <div class="item-second-row item-flex-growing item-contact-inf-mr">
      <div class="itm-con-block itm-con-align-right">
        <div class="itm-con-inline-block">
          <div class="fa-margin-right">
          <i class="fas fa-mobile-alt fa-lg header-fa-color-red h-fa-font-size"></i>
          </div>
        </div>
        <p class="p-inline-block text-color-white font-size">+123 456 7890</p>
      </div>
      <p class="p-con-block p-con-align-right text-color-gray" style="font-size: 14px;"><span class="displ-blok">MON-FRI: 8:30AM-7:30PM;  </span><span>SAT-SUN:9:30AM-4:30PM</span></p>
    </div>

    <div class="item-logo item-flex-growing itm-con-align-center">
      <div class="itm-con-align-left">
        <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/logo-image.jpg'); ?>" class="img-left"  />
      </div>
    </div>

  </div>
</div>

</div>

</div>


<div class="navigation-menu-whole">
  <div class="navigation-menu text-color-nav-white">
    <div class="nav-menu-part-home nm-part-margin-top">HOME</div>
    <div class="nav-menu-part nm-part-margin-top">SERVICES</div>
    <div class="nav-menu-part nm-part-margin-top">ABOUT</div>
    <div class="nav-menu-part nm-part-margin-top">REVIEWS</div>
    <div class="nav-menu-part nm-part-margin-top">LOCATIONS</div>
    <div class="nav-menu-part nm-part-margin-top">CONTACTS</div>
  </div>
</div>

  <img src="<?php echo $this->getViewFileUrl('Dejan_NovModul::images/under-nav-menu.jpg'); ?>" width="100%" height="auto" />

<div class="images-row">
    <div class="first-image">
      <h2 class="white-text">HEADLIGHTS</h2>
      <p class="gray-text">Headlights projector, LED, Factory</p>
    </div>
    <div class="second-image">
      <h2 class="white-text">HEADLIGHTS</h2>
      <p class="gray-text">Headlights projector, LED, Factory</p>
    </div>
</div>
<div class="images-row">
    <div class="third-image">
      <h2 class="white-text">HEADLIGHTS</h2>
      <p class="gray-text">Headlights projector, LED, Factory</p>
    </div>
    <div class="forth-image">
      <h2 class="white-text">HEADLIGHTS</h2>
      <p class="gray-text">Headlights projector, LED, Factory</p>
     </div>
</div>

<div class="container-fluid products">
  <div class="container-fluid inside-products">

    <div class="container-fluid featured-products">
        <div class="featured-product-inside">
        <h2 class="featured-color-white">FEATURED PRODUCTS</h2>
        <div class="featured-horizontal-line"></div>
        </div>
    </div>

      <div class="first-product products_margin">
          <h4 class="product-text-red">HEADLIGHTS</h4>
          <p class="product-text-white">300$</p>
          <div class="product-fa-icons fa-icons-margin-bottom">
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star-half-alt fa-xs"></i>
          </div>
      </div>
      <div class="second-product products_margin">
          <h4 class="product-text-red">HEADLIGHTS</h4>
          <p class="product-text-white">300$</p>
          <div class="product-fa-icons fa-icons-margin-bottom">
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star-half-alt fa-xs"></i>
          </div>
      </div>
      <div class="third-product products_margin">
          <h4 class="product-text-red">HEADLIGHTS</h4>
          <p class="product-text-white">300$</p>
          <div class="product-fa-icons fa-icons-margin-bottom">
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star-half-alt fa-xs"></i>
          </div>
      </div>
      <div class="forth-product products_margin">
          <h4 class="product-text-red">HEADLIGHTS</h4>
          <p class="product-text-white">300$</p>
          <div class="product-fa-icons fa-icons-margin-bottom">
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star-half-alt fa-xs"></i>
          </div>
      </div>
      <div class="fifth-product products_margin">
          <h4 class="product-text-red">HEADLIGHTS</h4>
          <p class="product-text-white">300$</p>
          <div class="product-fa-icons fa-icons-margin-bottom">
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star fa-xs"></i>
            <i class="fas fa-star-half-alt fa-xs"></i>
          </div>
      </div>

  </div>
  
</div>





<div class="before-footer-links-main">
  <div class="before-footer-links">
    <div class="bfl-first-div bfl-text-white">
      <p class="bfl-text-area-margin">25% OFF</p>
      <p class="bfl-second-p">ON ORDER OVER $999</p>
      <p class="bfl-third-p">This Offer is valid on all our items</p>
      <button class="bfl-button">BUY NOW</button>
    </div>

    <div class="bfl-vertical-line">
      
    </div>

    <div class="bfl-second-div bfl-text-white">
      <p class="bfl-text-area-margin">25% OFF</p>
      <p class="bfl-second-p">ON ORDER OVER $999</p>
      <p class="bfl-third-p">This Offer is valid on all our items</p>
      <button type="button" class="bfl-button">BUY NOW</button>
    </div>
  </div>
</div>


<div class="quick-links">
  <div class="container-fluid quick-links-row ">
    <div class="quick-links-item">
      <h5 class="quick-links-tit-white">QUICK LINKS</h5>
      <div class="quick-links-horisontal-line"></div>
      <p>About Us</p>
      <p>Customer Service</p>
      <p>Privacy Policy</p>
      <p>Site Map</p>
      <p>Search Terms</p>
      <p>Advanced Search</p>
      <p>Order and Returns</p>
      <p>Contact Us</p>
    </div>
    
    <div class="quick-links-item">
      <h5 class="quick-links-tit-white">QUICK LINKS</h5>
      <div class="quick-links-horisontal-line"></div>
      <p>About Us</p>
      <p>Customer Service</p>
      <p>Privacy Policy</p>
      <p>Site Map</p>
      <p>Search Terms</p>
      <p>Advanced Search</p>
      <p>Order and Returns</p>
      <p>Contact Us</p>
    </div>

    <div class="quick-links-item">
      <h5 class="quick-links-tit-white">QUICK LINKS</h5>
      <div class="quick-links-horisontal-line"></div>
      <p>About Us</p>
      <p>Customer Service</p>
      <p>Privacy Policy</p>
      <p>Site Map</p>
      <p>Search Terms</p>
      <p>Advanced Search</p>
      <p>Order and Returns</p>
      <p>Contact Us</p>
    </div>

    <div class="quick-links-news">
      <h5 class="quick-links-tit-white">NEWSLETTER</h5>
      <div class="quick-links-horisontal-line"></div>
      <p><span class="news-span-display-block">Lorem ipsum dolor sit amet, consectetur adi-</span>
      <span class="news-span-display-block">piscing elit, sed do eiusmod tempor incididunt</span></p>
      <input type="search" class="news-input-search" name="">
      <button class="news-button">SUBMIT</button>
      <div class="social-media-fa-icons">
        <i class="fab fa-facebook-f display-inline"></i>
        <i class="fab fa-twitter display-inline"></i>
        <i class="fab fa-google-plus-g display-inline"></i>
        <i class="fab fa-instagram display-inline"></i>
        <i class="fab fa-pinterest-square display-inline"></i>
      </div>
    </div>

  </div>
</div>


  <div class="footer-horisontal-line">
    <div class="footer-horizontal-style"></div>
  </div>


<div class="footer-main">
  <div class="container-fluid footer-row footer-fa-red">

    <div class="footer-item">
      <h5 class="footer-tit-white">INFORMATION</h5>
      <div class="footer-small-horisontal-line"></div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <div class="footer-item">
      <h5 class="footer-tit-white">INFORMATION</h5>
      <div class="footer-small-horisontal-line"></div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <div class="footer-information">
      <h5 class="footer-tit-white">CONTACT</h5>
      <div class="footer-small-horisontal-line"></div>
      <div>
        <i class="fas fa-map-marker-alt footer-fa-red"></i>
        <p class="footer-paragraph-inline">123, Main Road, Your City, NY 1234</p>
      </div>
      <div>
        <i class="fas fa-phone-square footer-fa-red "></i>
        <p class="footer-paragraph-inline">+123 456 7890</p>
      </div>
      <div>
        <i class="fas fa-clock footer-fa-red"></i>
        <p class="footer-paragraph-inline">7 Days a week from 10:00 am to 6:00 pm</p>
      </div>
      <div>
        <i class="fas fa-envelope footer-fa-red"></i>
        <p class="footer-paragraph-inline">info@psdfreebies.com</p>
      </div>
    </div>

  </div>
</div>

  <div class="footer-horisontal-line">
    <div class="footer-horizontal-style"></div>
  </div>


<div class="footer-end-main">
  <div class="container-fluid footer-end">
    <i class="fab fa-cc-amex fa-icons-display-inline"></i>
    <i class="fab fa-cc-paypal fa-icons-display-inline"></i>
    <i class="fab fa-cc-visa fa-icons-display-inline"></i>
    <i class="fab fa-cc-mastercard fa-icons-display-inline"></i>
    <i class="fas fa-closed-captioning fa-icons-display-inline"></i>
    </div>
  </div>
</div>